{"name": "test_16_validate_data_from_xl_file", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <main.TestCases object at 0x000002343AF1CE10>\n\n    def test_16_validate_data_from_xl_file(self):\n        self.xlutils = XLUtils(self.driver)\n        self.homepage = HomePage(self.driver)\n        rows, columns = self.xlutils.get_row_col_count(Locators.product_name_data_file_path, \"Sheet1\")\n        product_name_list = self.homepage.get_all_product_names()\n        for r in range(1, rows + 1):\n            data = self.xlutils.get_data(Locators.product_name_data_file_path, \"Sheet1\", r, 1)\n>           assert data == product_name_list[r - 1], \"UI data does not match with excel sheet!\"\nE           IndexError: list index out of range\n\nmain.py:263: IndexError"}, "start": 1695611412879, "stop": 1695611422909, "uuid": "18e19d0e-369a-4808-9bf1-1dd6f62c0d83", "historyId": "b3e75ecc86b3bdf94caf750f170cbc16", "testCaseId": "b3e75ecc86b3bdf94caf750f170cbc16", "fullName": "main.TestCases#test_16_validate_data_from_xl_file", "labels": [{"name": "suite", "value": "main"}, {"name": "subSuite", "value": "TestCases"}, {"name": "host", "value": "TCL5CD241DL2B"}, {"name": "thread", "value": "620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}